name: 'Security Trivy Critical Scan'
description: 'Runs Trivy to scan for critical vulnerabilities and uploads results to GitHub Security tab (will not fail).'
inputs:
  skip-files:
    description: 'Comma-separated list of file paths to skip in Trivy scan.'
    required: false
    default: ''
  trivyignores:
    description: 'Comma-separated list of .trivyignore files to use'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
        skip-files: ${{ inputs.skip-files }}
        trivyignores: ${{ inputs.trivyignores }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@fe4161a26a8629af62121b670040955b330f9af2 # v4.31.6
      with:
        sarif_file: 'trivy-results.sarif'
