name: 'Specific helmfile linter'
description: 'This action validate all environments in a helmfile with sops secret'
inputs:
  docker-build-args:
    description: 'The docker build args without -t'
    required: true
  docker-image-name:
    description: 'The docker image name'
    required: true
  docker-context:
    description: 'The docker build context path'
    required: false
    default: '.'
  trivyignores:
    description: 'Comma-separated list of .trivyignore files to use'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    -
      name: Build an image from Dockerfile
      run: |
         docker build ${{ inputs.docker-build-args }} -t ${{ inputs.docker-image-name }} ${{ inputs.docker-context }}
      shell: bash
    -
      name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash
    -
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: trivy
        key: ${{ steps.get-date.outputs.date }}
        save-always: true
    -
      name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        image-ref: "${{ inputs.docker-image-name }}"
        format: 'table'
        exit-code: '1'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        cache-dir: trivy
        trivyignores: ${{ inputs.trivyignores }}
    -
      name: Fix trivy cache folder permission
      if: always()
      run: |
        sudo chown -R $DOCKER_USER trivy
      shell: bash
